version: '3.8'

services:
  api:
    build: .
    container_name: hello-jenkins-api
    ports:
      - "8000:8000"
    environment:
      # Inject dari environment luar (Jenkins)
      - MESSAGE=${MESSAGE}
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: hello-jenkins-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  umur_api:
    build: 
      context: ./age-app
    container_name: umur-api
    depends_on:
      - redis
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api

volumes:
  caddy_data:
  caddy_config:
  redis_data:
